image: woss/pnpm

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
variables:
  NODE_ENV: ci

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .pnpm-store
  policy: pull-push

.before_script_install_deps_template:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  before_script:
    - pnpm i

stages:
  - dependencies
  - test
  - lint
  - docs
  - build

dependencies:
  stage: dependencies
  before_script:
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
# lint:
#   extends: .before_script_install_deps_template
#   stage: lint
#   needs: [dependencies]
#   script:
#     - pnpm lint

test:
  extends: .before_script_install_deps_template
  stage: test
  needs: [dependencies]
  script:
    - pnpm i && pnpm test:coverage -- --testPathIgnorePatterns operations
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  tags:
    - docker
# pages:
#   stage: docs
#   needs: [dependencies]
#   script:
#     - pnpm docs
#   artifacts:
#     paths:
#       - public
#   only:
#     - master

# build:
#   stage: build
#   needs: [dependencies, test]
#   script:
#     - pnpm build
#   only:
#     - merge_requests
