tasks:
  - name: install the remote-signer
    before: |
      sudo sh -c 'curl https://ipfs.anagolay.network/ipfs/bafybeicurfm4pbyyf6iqlj26bvmwr6cperfuimgo734ls7fj2umgmmbawq > /usr/local/bin/remote-signer && chmod +x /usr/local/bin/remote-signer' \
      && git config --global gpg.program "remote-signer" \
      && git config --global commit.gpgsign true

vscode:
  extensions:
    - PKief.material-icon-theme
    - esbenp.prettier-vscode
    - donjayamanne.githistory
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - dbaeumer.vscode-eslint
    - mongodb.mongodb-vscode
    - foxundermoon.shell-format
    - streetsidesoftware.code-spell-checker
    - mhutchie.git-graph
    - PKief.material-icon-theme
    - ms-azuretools.vscode-docker
    - eg2.vscode-npm-script
    - pflannery.vscode-versionlens
    - formulahendry.auto-rename-tag
