# https://docs.gitlab.com/ee/ci/jobs/job_control.html
image: node:16-bullseye
stages:
  - test
  - release

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - common/temp/
    - ANAGOLAY_CLI_CID
    - ANAGOLAY_CUSTOM_TYPES_CID

variables:
  IPFS_PATH: .ipfs

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-draft$/
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# include this where you need it. like in before_script
.install-ipfs-and-setup: &install-ipfs-and-setup
  - echo "Downloading the go-ipfs binary v0.12.0 from our IPFS node"
  - |
    curl https://ipfs.anagolay.network/ipfs/bafybeih63m5xkkskklntu3ufd6kyjgkvqot4bcre3evquindven7i6yxse > /usr/local/bin/ipfs
    chmod +x /usr/local/bin/ipfs
    mkdir $IPFS_PATH
    echo "/ip4/${ANAGOLAY_MAIN_IPFS_IP}/tcp/${ANAGOLAY_MAIN_IPFS_PORT}" > $IPFS_PATH/api

# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts
.install-pnpm: &install-pnpm
  - |
    curl https://ipfs.anagolay.network/ipfs/QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY > /usr/local/bin/pnpm
    chmod +x /usr/local/bin/pnpm
    node --version
    pnpm --version
    git --version

test-and-build:
  stage: test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  before_script:
    - *install-pnpm
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    # - echo 'Checking for missing change logs...'
    # - node common/scripts/install-run-rush.js change -v

    - echo 'Building and testing all packages...'
    - node common/scripts/install-run-rush.js rebuild --verbose

build-js-api-docs:
  stage: release
  before_script:
    - *install-pnpm
    - pnpm add -g @microsoft/api-documenter
    - *install-ipfs-and-setup
  script:
    - set -e
    - api-documenter markdown -i ./api-extractor-docs/json -o ./apps/anagolay.dev/docs/js-api
    - ls -la ./apps/anagolay.dev/docs/js-api

    # - echo "Install the docusaurus dependencies"
    # - pnpm install

    # - echo "Build the docs website"
    # - pnpm build

    # - echo "Uploading CLI to IPFS ..."
    # - ipfs add --cid-version=1 --pin=false --recursive --quieter ./docs/published/build > ANAGOLAY_JS_API_DOCS
    # - echo "The docs are published here https://ipfs.anagolay.network/ipfs/$(cat ANAGOLAY_JS_API_DOCS)

upload-cli-to-ipfs:
  needs: ['test-and-build']
  stage: release
  before_script:
    - *install-ipfs-and-setup
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    - echo 'Building from CLI ...'
    - node common/scripts/install-run-rush.js rebuild --from @anagolay/cli

    - echo "Uploading CLI to IPFS ..."
    - ipfs add --cid-version=1 --pin=true --recursive --quieter sdk/cli/dist/anagolay.js > ANAGOLAY_CLI_CID
    - echo "The CLI is published with the CID:" && cat ANAGOLAY_CLI_CID
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

upload-custom-types-to-ipfs:
  stage: release
  before_script:
    - *install-ipfs-and-setup
  script:
    - set -e

    - echo "Uploading Custom types to IPFS ..."
    - ipfs add --cid-version=1 --pin=true --recursive --quieter sdk/types/src/customTypes.json > ANAGOLAY_CUSTOM_TYPES_CID
    - echo "The Custom Types are published with the CID:" && cat ANAGOLAY_CUSTOM_TYPES_CID
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
