# https://docs.gitlab.com/ee/ci/jobs/job_control.html
image: node:18-bullseye
stages:
  - check
  - test
  - release

variables:
  PNPM_IPFS_CID: QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY
  ANAGOLAY_IPFS_CLI_CID: bafybeigiuuavnlqy7czvxlvxdrqzcsvm7ezfkbbq4jwksl77lk5f7tlhia

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - common/temp/
    - ANAGOLAY_CLI_JS_CID
    - ANAGOLAY_CLI_BIN_CID
    - ANAGOLAY_CUSTOM_TYPES_CID

# workflow:
#   rules:
#     - if: $CI_COMMIT_MESSAGE =~ /-draft$/
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# include:
#   - template: Security/Dependency-Scanning.gitlab-ci.yml
#   - template: Security/License-Scanning.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml

# include this where you need it. like in before_script
.install-ipfs-cli-and-setup: &install-ipfs-cli-and-setup
  - echo "Downloading anagolay ipfs CLI which works with the ipfsAuthProxy."
  - |
    curl https://ipfs.anagolay.network/ipfs/"$ANAGOLAY_IPFS_CLI_CID" > /usr/local/bin/ipfsCli
    chmod +x /usr/local/bin/ipfsCli

# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts
.install-pnpm: &install-pnpm
  - |
    curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    pnpm config set store-dir common/temp/pnpm-store
    node --version
    pnpm --version
    git --version

is-it-pretty:
  stage: check
  before_script:
    - *install-pnpm
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    - echo 'Is our code pretty?'
    - node common/scripts/install-run-rush.js prettier:check

test-code:
  needs: ['is-it-pretty']
  stage: test
  before_script:
    - *install-pnpm
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    # - echo 'Checking for missing change logs...'
    # - node common/scripts/install-run-rush.js change -v

    - echo 'Building and testing all packages...'
    - node common/scripts/install-run-rush.js rebuild --verbose

# build-js-api-docs:
#   stage: release
#   before_script:
#     - *install-pnpm
#     - pnpm add -g @microsoft/api-documenter
#     - *install-ipfs-cli-and-setup
#   script:
#     - set -e
#     - api-documenter markdown -i ./api-extractor-docs/json -o ./apps/anagolay.dev/docs/js-api
#     - ls -la ./apps/anagolay.dev/docs/js-api

#     # - echo "Install the docusaurus dependencies"
#     # - pnpm install

#     # - echo "Build the docs website"
#     # - pnpm build

#     # - echo "Uploading CLI to IPFS ..."
#     # - ipfs add --cid-version=1 --pin=false --recursive --quieter ./docs/published/build > ANAGOLAY_JS_API_DOCS
#     # - echo "The docs are published here https://ipfs.anagolay.network/ipfs/$(cat ANAGOLAY_JS_API_DOCS)

upload-cli-to-ipfs:
  needs: ['test-code']
  stage: release
  before_script:
    - *install-pnpm
    - *install-ipfs-cli-and-setup
  script:
    - set -e

    - echo 'Installing rush...'
    - node common/scripts/install-run-rush.js install

    - echo 'Building from CLI ...'
    - node common/scripts/install-run-rush.js rebuild --from @anagolay/cli

    - echo "Uploading CLI to IPFS ..."
    - ipfsCli add --pin --onlyCid sdk/cli/dist/anagolay.js > ANAGOLAY_CLI_JS_CID
    - echo "The JS CLI version CID:" && cat ANAGOLAY_CLI_JS_CID
    - echo "https://$(cat ANAGOLAY_CLI_JS_CID).ipfs.anagolay.network?filename=anagolay"

    - ipfsCli add --pin --onlyCid sdk/cli/binaries/anagolay > ANAGOLAY_CLI_BIN_CID
    - echo "The BINARY CLI version CID:" && cat ANAGOLAY_CLI_BIN_CID
    - echo "https://$(cat ANAGOLAY_CLI_BIN_CID).ipfs.anagolay.network?filename=anagolay"

  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

upload-custom-types-to-ipfs:
  stage: release
  before_script:
    - *install-ipfs-cli-and-setup
  script:
    - set -e

    - echo "Uploading Custom types to IPFS ..."
    - ipfsCli add --pin --onlyCid sdk/types/src/customTypes.json > ANAGOLAY_CUSTOM_TYPES_CID
    - echo "The Custom Types are published with the CID:" && cat ANAGOLAY_CUSTOM_TYPES_CID
    - echo "https://ipfs.anagolay.network/ipfs/$(cat ANAGOLAY_CUSTOM_TYPES_CID)"

  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^.*\[build all\].*$/s
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
