image: docker.io/woss/gitpod-workspace:gitpod_workspace-full_2022-05-08-14-31-53
tasks:
  - name: prep-env
    init: pnpm env use --global 18.4.0 && node $GITPOD_REPO_ROOT/common/scripts/install-run-rush.js update && exit

vscode:
  extensions:
    - PKief.material-icon-theme
    - esbenp.prettier-vscode
    - donjayamanne.githistory
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - dbaeumer.vscode-eslint
    - mongodb.mongodb-vscode
    - foxundermoon.shell-format
    - streetsidesoftware.code-spell-checker
    - mhutchie.git-graph
    - PKief.material-icon-theme
    - ms-azuretools.vscode-docker
    - eg2.vscode-npm-script
    - pflannery.vscode-versionlens
    - formulahendry.auto-rename-tag
