image: node:14

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - template: Dependency-Scanning.gitlab-ci.yml

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - dependencies
  - test
  - lint
  - docs

dependencies:
  stage: dependencies
  script:
    - yarn

lint:
  stage: lint
  needs: [dependencies, test_all_with_coverage]
  script:
    - yarn std

test_all_with_coverage:
  stage: test
  needs: [dependencies]
  script:
    - yarn test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  tags:
    - docker

pages:
  stage: docs
  needs: [dependencies]
  script:
    - yarn docs
  artifacts:
    paths:
      - public
  only:
    - master
