image: node:14

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
variables:
  NODE_ENV: ci

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - dependencies
  - test
  - lint
  - docs
  - build

dependencies:
  stage: dependencies
  script:
    - yarn

lint:
  stage: lint
  needs: [dependencies]
  script:
    - yarn lint

test:
  stage: test
  needs: [dependencies]
  script:
    - yarn test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  tags:
    - docker

pages:
  stage: docs
  needs: [dependencies]
  script:
    - yarn docs
  artifacts:
    paths:
      - public
  only:
    - master

build:
  stage: build
  needs: [dependencies, test]
  script:
    - yarn build
  only:
    - merge_requests
