default:
  image: docker.io/node:18.4.0-bullseye

stages:
  - lint
  - test
  - build
  - pre-publish
  - publish
  - upload

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - common/temp
    - app/.svelte-kit
    - app/build

### workflows control when to create the PIPELINE, not jobs
workflow:
  rules:
    - if: $FORCE_START
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_MESSAGE =~ /^.*\[mellon\].*$]/ # a friendly tag so we can test it
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" ## this is the same as $CI_MERGE_REQUEST_IID

variables:
  NODE_ENV: 'test'
  PNPM_IPFS_CID: QmeCUX9cK4YKdTbNVq3jg5cJPvz8uQiQmb4AKKd7niy4kY
  ANAGOLAY_IPFS_CLI_CID: bafybeigiuuavnlqy7czvxlvxdrqzcsvm7ezfkbbq4jwksl77lk5f7tlhia

include:
  - local: .devops/ci/gitlab/**/*.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
