image: node:14

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    # - .yarn

stages:
  - deps
  - test
  - docs

dependencies:
  stage: deps
  script:
    - yarn

lint:
  stage: test
  needs: [dependencies]
  script:
    - yarn std

test_all_with_coverage:
  stage: test
  needs: [dependencies]
  script:
    - yarn test:coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  tags:
    - docker

pages:
  stage: docs
  needs: [dependencies]
  script:
    - yarn docs
  artifacts:
    paths:
      - public
  only:
    - master
