image: docker.io/woss/gitpod-workspace:gitpod_workspace-full_2022-05-08-14-31-53
tasks:
  - name: prep-env
    init: |
      nix-env -f '<nixpkgs>' -iA nix-direnv nixpkgs-fmt
      node $GITPOD_REPO_ROOT/common/scripts/install-run-rush.js update
      node $GITPOD_REPO_ROOT/common/scripts/install-run-rush.js build
      exit
  - name: Start stuff
    command: bash $GITPOD_REPO_ROOT/.devops/gitpod/start-cmd.sh && exit

ports:
  - port: 7766
    visibility: public
    onOpen: ignore
# onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - donjayamanne.githistory
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - dbaeumer.vscode-eslint
    - foxundermoon.shell-format
    - streetsidesoftware.code-spell-checker
    - mhutchie.git-graph
    - PKief.material-icon-theme
    - ms-azuretools.vscode-docker
    - eg2.vscode-npm-script
    - pflannery.vscode-versionlens
    - formulahendry.auto-rename-tag
    - asciidoctor.asciidoctor-vscode
